In [4]:
import numpy as np

In [8]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [10]:
arr1.shape

(5,)

In [12]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr2.shape

(2, 3)

In [16]:
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
arr3.shape

(2, 2, 2)

In [20]:
arr3.ndim

3

In [22]:
arr2.ndim

2

In [24]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr1

array([1, 2, 3, 4, 5])

In [30]:
arr1.ndim

1

In [32]:
arr1.size

5

In [34]:
arr3.size

8

In [40]:
arr3.itemsize

4

In [42]:
arr3.dtype

dtype('int32')

In [46]:
arr3.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])