In [2]:
import numpy as np

In [6]:
arr=np.random.randint(low=1,high=100,size=20).reshape(4,5)
arr

array([[44,  8, 83, 92, 38],
       [89, 56, 86, 94, 98],
       [ 5, 95, 28, 24, 58],
       [67, 19, 97, 51, 56]])

In [8]:
arr[0]

array([44,  8, 83, 92, 38])

In [10]:
arr[0][2]

83

In [12]:
arr>50

array([[False, False,  True,  True, False],
       [ True,  True,  True,  True,  True],
       [False,  True, False, False,  True],
       [ True, False,  True,  True,  True]])

In [14]:
(arr>50).shape

(4, 5)

In [18]:
#indexing using bollean array
arr[arr>50]


array([83, 92, 89, 56, 86, 94, 98, 95, 58, 67, 97, 51, 56])

In [22]:
arr[(arr>50)&(arr%2!=0)]

array([83, 89, 95, 67, 97, 51])

In [24]:
arr[(arr>50)&(arr%2!=0)]=0
arr

array([[44,  8,  0, 92, 38],
       [ 0, 56, 86, 94, 98],
       [ 5,  0, 28, 24, 58],
       [ 0, 19,  0,  0, 56]])