In [2]:
import numpy as np

In [4]:
np.random.random()

0.2504944889312214

In [8]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [10]:
np.random.uniform(100)

28.687875149226343

In [12]:
np.random.uniform(1,100,10)

array([ 1.01132311, 30.93092469, 15.52883319, 10.14152088, 19.43976093,
       35.21051198, 40.27997995, 54.34285667, 42.50025693, 68.83673054])

In [14]:
np.random.uniform(1,100,10).reshape(2,5)

array([[21.24077272, 87.9336262 ,  3.71137173, 67.37628351, 42.31317543],
       [56.31029302, 14.89830692, 20.61204742, 80.2737123 , 96.857896  ]])

In [18]:
np.random.randint(1,10)

7

In [20]:
np.random.randint(1,10,5)

array([2, 1, 2, 9, 9])

In [26]:
np.random.randint(1,10,15).reshape(3,5)

array([[6, 2, 4, 5, 9],
       [2, 5, 1, 4, 3],
       [1, 5, 3, 8, 8]])

In [28]:
a=np.random.randint(1,10,6)

In [30]:
a

array([9, 7, 4, 8, 8, 5])

In [34]:
np.max(a)

9

In [36]:
np.min(a)

4

In [38]:
np.argmax(a)

0

In [40]:
a[np.argmin(a)]

4

In [42]:
np.argmin(a)

2

In [44]:
a=np.random.randint(1,10,6)

In [46]:
a


array([6, 4, 7, 9, 1, 3])

In [48]:
a[a%2==1]=-1
a

array([ 6,  4, -1, -1, -1, -1])

In [50]:
a=np.random.randint(1,50,6)
a

array([11, 24, 16, 48, 24, 26])

In [54]:
np.where(a%2==1,-1,a)

array([-1, 24, 16, 48, 24, 26])

In [56]:
a


array([11, 24, 16, 48, 24, 26])

In [58]:
out=np.where(a%2==1,-1,a)

In [60]:
out

array([-1, 24, 16, 48, 24, 26])

In [62]:
a=np.random.randint(1,50,6)
a

array([ 8, 29, 11, 47, 33, 25])

In [66]:
a=np.sort(a)
a

array([ 8, 11, 25, 29, 33, 47])

In [68]:
np.percentile(a,25)

14.5

In [70]:
np.percentile(a,50)

27.0

In [72]:
np.percentile(a,99.8)

46.86