In [2]:
import numpy as np

In [4]:
lista=range(100)
arr11=np.arange(100)

In [6]:
import sys

In [8]:
print(sys.getsizeof(87)*len(lista))

2800


In [10]:
print(arr11.itemsize*arr11.size)

400


In [12]:
import time

In [14]:
x=range(100000)
y=range(100000,200000)
start_time=time.time()

c=[(x,y) for x,y in zip(x,y)]


print(time.time()-start_time)

0.02639293670654297


In [16]:
a=np.arange(100000)
b=np.arange(100000,200000)

start_time=time.time()

c=a+b

print(time.time()-start_time)

0.007214069366455078


In [18]:
arr12=np.arange(24)
arr12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
arr12=np.arange(24).reshape(12,2)
arr12

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [24]:
arr12=np.arange(24).reshape(2,12)
arr12

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [26]:
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [28]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
arr12[2]


array([ 8,  9, 10, 11])

In [32]:
arr12[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [36]:
arr12[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [38]:
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [40]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [42]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [44]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
