In [2]:
import numpy as np


In [4]:
lista=range(100)
arr11=np.arange(100)

In [6]:
import sys


In [8]:
print(sys.getsizeof(87)*len(lista))

2800


In [10]:
print(arr11.itemsize*arr11.size)

400


In [12]:
import time

In [14]:
x=range(100000)
y=range(100000,200000)
start_time=time.time()

c=[(x,y) for x,y in zip(x,y)]


print(time.time()-start_time)

0.015983104705810547


In [16]:
a=np.arange(100000)
b=np.arange(100000,200000)

start_time=time.time()

c=a+b

print(time.time()-start_time)

0.006016731262207031


In [18]:
arr12=np.arange(24)
arr12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [26]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [28]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])


In [30]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [32]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [34]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [38]:
arr2>3

array([ True,  True,  True,  True,  True,  True])

In [40]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [42]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [44]:
arr1.dot(arr2)

154

In [46]:
arr1.dot(arr3)

ValueError: shapes (6,) and (2,3) not aligned: 6 (dim 0) != 2 (dim 0)

In [48]:
arr4.max()

11

In [50]:
arr4.min()

6

In [52]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [56]:
arr4.min(axis=0)

array([6, 7])

In [58]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [60]:
arr4.sum()

51

In [62]:
arr4.sum(axis=0)

array([24, 27])

In [64]:
arr4.mean()

8.5

In [66]:
arr4.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [68]:
arr4.std()

1.707825127659933

In [70]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [72]:
np.median(arr4)

8.5

In [74]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])